// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGY4VWfpNTmPz5rh1V0MFxG9t76fa279Y',
    appId: '1:634610145670:web:d001393890781689ed3407',
    messagingSenderId: '634610145670',
    projectId: 'my-firebase-efbe8',
    authDomain: 'my-firebase-efbe8.firebaseapp.com',
    storageBucket: 'my-firebase-efbe8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDab8k9e4Ugy3CGqTdsLZRyxcpvk8H8qj4',
    appId: '1:634610145670:android:7eaacc849d1002caed3407',
    messagingSenderId: '634610145670',
    projectId: 'my-firebase-efbe8',
    storageBucket: 'my-firebase-efbe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfOeFDqTsSoNVLudCQchN2ANNzZlkhng4',
    appId: '1:634610145670:ios:eccd44b42e445ad5ed3407',
    messagingSenderId: '634610145670',
    projectId: 'my-firebase-efbe8',
    storageBucket: 'my-firebase-efbe8.firebasestorage.app',
    iosBundleId: 'com.example.infoSaldoApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfOeFDqTsSoNVLudCQchN2ANNzZlkhng4',
    appId: '1:634610145670:ios:eccd44b42e445ad5ed3407',
    messagingSenderId: '634610145670',
    projectId: 'my-firebase-efbe8',
    storageBucket: 'my-firebase-efbe8.firebasestorage.app',
    iosBundleId: 'com.example.infoSaldoApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGY4VWfpNTmPz5rh1V0MFxG9t76fa279Y',
    appId: '1:634610145670:web:3c2879fd9b088141ed3407',
    messagingSenderId: '634610145670',
    projectId: 'my-firebase-efbe8',
    authDomain: 'my-firebase-efbe8.firebaseapp.com',
    storageBucket: 'my-firebase-efbe8.firebasestorage.app',
  );

}